### ISSUE TITLE
An exception occurred while querying data

### ISSUE THREAD

**Issue by yjclsx** [questdb/questdb#1490]
### Describe the bug

```
2021-10-27 19:44:43.692 [pool-3-thread-7811] DEBUG c.s.m.q.CaptureResultMapper.getCaptureListByTime - ==>  Preparing: select * from capture_result_4_20211027 where cameraNo = ? and actionTime >= ? and actionTime < ? order by actionTime 
2021-10-27 19:44:43.692 [pool-3-thread-7811] DEBUG c.s.m.q.CaptureResultMapper.getCaptureListByTime - ==> Parameters: 16827(Integer), 2021-10-27 04:30:00(String), 2021-10-27 04:35:00(String)
2021-10-27 19:44:43.698 [pool-3-thread-7811] INFO  c.s.service.impl.quest.CaptureResultServiceImpl - 获取capture_result_4_20211027数据失败,error:
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: [0]: max txn-inflight limit reached [txn=201417, min=176665]
  Position: 15
### The error may exist in com/secusoft/mapper/quest/CaptureResultMapper.java (best guess)
### The error may involve com.secusoft.mapper.quest.CaptureResultMapper.getCaptureListByTime-Inline
### The error occurred while setting parameters
### SQL: select * from capture_result_4_20211027 where cameraNo = ? and actionTime >= ? and actionTime < ? order by actionTime
### Cause: org.postgresql.util.PSQLException: ERROR: [0]: max txn-inflight limit reached [txn=201417, min=176665]
  Position: 15
; uncategorized SQLException for SQL []; SQL state [00000]; error code [0]; ERROR: [0]: max txn-inflight limit reached [txn=201417, min=176665]
  Position: 15; nested exception is org.postgresql.util.PSQLException: ERROR: [0]: max txn-inflight limit reached [txn=201417, min=176665]
  Position: 15
```

### Environment

```markdown
- **QuestDB version**: 6.0.5
- **OS**:
- **Browser**:
```

**Comment by bsmth** [comment]
Hi @yjclsx thanks for raising the issue. It looks like this [stack overflow question](https://stackoverflow.com/questions/67785629/what-does-max-txn-txn-inflight-limit-reached-in-questdb-and-how-to-i-avoid-it) describes the same error. Could you try the suggested fix there?

**Comment by yjclsx** [comment]
Thank you for your reply. I tried to delete the file “_txn_scoreboard”, but it was generated again when I did the INSERT, and the error occurred some time later.

**Comment by ideoma** [comment]
This can be a symptom of not closing connections. to the database.  What framework / connection lifecycle to you use to query QuestDB?

**Comment by yjclsx** [comment]
I use Postgres to quest data, and the connection framework is Druid. like this:
`Class.forName("org.postgresql.Driver");
Properties props = new Properties();
props.put("driverClassName", "org.postgresql.Driver");
props.put("url", "jdbc:postgresql://"+host+":"+port+"/"+dbName);
props.put("username", userName);
props.put("password", password);
props.put("initialSize", "1");
props.put("minIdle", "1");
props.put("maxActive", "10");
DataSource dataSource = DruidDataSourceFactory.createDataSource(props);

...

Connection connection = dataSource.getConnection();
try (PreparedStatement preparedStatement = connection.prepareStatement("select * from "+tableName+" where cameraNo = ? and actionTime >= ? and actionTime < ? order by actionTime")) {
	preparedStatement.setQueryTimeout(10);
    ResultSet rs = preparedStatement.executeQuery();
    while (rs.next()) {
		...
	}
} catch (SQLException e) {
    log.error("Select QuestDB Error",e);
}`

**Comment by yjclsx** [comment]
I use Postgres to quest data, and the connection framework is Druid. like this:
`Class.forName("org.postgresql.Driver");
Properties props = new Properties();
props.put("driverClassName", "org.postgresql.Driver");
props.put("url", "jdbc:postgresql://"+host+":"+port+"/"+dbName);
props.put("username", userName);
props.put("password", password);
props.put("initialSize", "1");
props.put("minIdle", "1");
props.put("maxActive", "10");
DataSource dataSource = DruidDataSourceFactory.createDataSource(props);

...

Connection connection = dataSource.getConnection();
try (PreparedStatement preparedStatement = connection.prepareStatement("select * from "+tableName+" where cameraNo = ? and actionTime >= ? and actionTime < ? order by actionTime")) {
	preparedStatement.setQueryTimeout(10);
    ResultSet rs = preparedStatement.executeQuery();
    while (rs.next()) {
		...
	}
} catch (SQLException e) {
    log.error("Select QuestDB Error",e);
}`

**Comment by ideoma** [comment]
This should be solved in 6.1.1

**Comment by JasperSui** [comment]
Hi @ideoma ,
I'm currently facing this issue with 6.1.2 QuestDB.

`max txn-inflight limit reached [txn=377284, min=360900]`

The connection backend I'm using is `postgresql_psycopg2` with Django, do you have any suggestions?
Thank you for your contribution!

**Comment by yjclsx** [comment]
已收到，会尽快查看，谢谢！(自动回复)

**Comment by fishuke** [comment]
It still exists in 2022 with the latest version.

**Comment by fishuke** [comment]
[0]: max txn-inflight limit reached [txn=17897, min=1513, size=16384]

**Comment by yjclsx** [comment]
已收到，会尽快查看，谢谢！(自动回复)

**Comment by stevenaldinger** [comment]
is it still safe to delete the `_txn_scoreboard` file? https://stackoverflow.com/questions/67785629/what-does-max-txn-txn-inflight-limit-reached-in-questdb-and-how-to-i-avoid-it

**Comment by yjclsx** [comment]
已收到，会尽快查看，谢谢！(自动回复)

**Comment by ideoma** [comment]
Please update QuestDB to the latest version, 7.0.1
Number of these errors are fixed in 6.x version #2441, #1759

**Comment by Balaji2810** [comment]
I'm using the latest version of QuestDB (v7.0.1). I still face this issue while querying the data.
`max txn-inflight limit reached [txn=3185098, min=3091937, size=16384]`

**Comment by chandler150** [comment]
Still facing this issue on 7.4.2, will look to update to 8 soon. First time we've ever seen it though, so sufficiently rare.

[0]: max txn-inflight limit reached [txn=11687237, min=11670853, size=16384]

**Comment by yjclsx** [comment]
已收到，会尽快查看，谢谢！(自动回复)
