### ISSUE TITLE
BETWEEN statement fills up memory

### ISSUE THREAD

**Issue by mariusziemke** [questdb/questdb#1680]
### Describe the bug

When running queries with `WHERE timestamp BETWEEN 'TIMESTAMP A' AND 'TIMESTAMP B'` memory consumption spikes and does not return to normal until a restart was performed.

I am using grafana with dashboard variables which perform some queries on dashboard load. 

e.g. `SELECT DISTINCT ID FROM 'testTable'  WHERE $__timeFilter(timestamp)`

Grafana replaces the timeFilter with the `WHERE timestamp BETWEEN X Y` statement and in my case, it uses the current timestamp and the timestamp from one hour ago which results in the query always being different. I guess that some kind of caching leads to this issue. 

### To reproduce

1. Create table as below
2. Insert some values
3. Run a few queries with different `BETWEEN` timestamps
4. Watch the memory allocation going up 

### Expected Behavior

Memory should not spike that much and should at least be freed again.

### Environment

```markdown
- **QuestDB version**: 6.1.2
- **OS**: Ubuntu 20.04
```

### Additional context

Memory consumption of QuestDB 

![Bildschirmfoto 2021-12-14 um 03 18 53](https://user-images.githubusercontent.com/27853515/145921082-b24b52ce-9279-4bcb-9748-b62a0b620f57.png)

My table design:

```
CREATE TABLE test(
    ID SYMBOL capacity 1048576 index,
    valueA DOUBLE,
    valueB DOUBLE,
    valueC DOUBLE,
    ts TIMESTAMP
) timestamp(ts);
```

**Comment by bluestreak01** [comment]
We test all of our SQL implementations for memory leaks, so memory leak is unlikely.

On other hand grafana plugin doesn't use bind variables, which makes questdb query caching inefficient. To reduce memory footprint I would suggest reducing cache size:

```
cairo.cache.rows=1
cairo.cache.blocks=1
```

**Comment by mariusziemke** [comment]
Thanks for responding so quickly! Just tried your settings, but it still fills up the memory the same way.. 

I played a bit more with the queries and it looks like query caching in general is using up my memory. So it is not specific to `BETWEEN`, but rather to unique queries as we are doing some dynamic regex matching too.

Could there be a relation to symbol caching? I've recreated the tables with disabled symbol caching and now I am waiting for a few million rows to be ingested.

I am still a bit confused why the memory is not freed up after some time - is this expected?

**Comment by ideoma** [comment]
This is memory mapped, it can be shown like process memory but in fact it is not physical RAM really. When table is queried it's data is mapped to memory and all gauges jump but and then OS reads into RAM from disk page by page lazily when the data is accessed. It also can map same physical RAM into multiple logical addresses expanding process virtual memory usage but not physical.

At the end, when OS will need to free up physical RAM it will discard unchanged mapped pages. You will see that QuestDB uses multiple times you physical RAM on queries (even on systems without swap) but it's virtual mapped memory, not physical.

If you want the char to look better you can reduce worker pool sizes trading off response times
https://questdb.io/docs/reference/configuration/#shared-worker but I'd not change it unless you see out of memory problems

**Comment by mariusziemke** [comment]
That makes sense.. I am just curious why the machine got unresponsive after the gauges jumped. It looked like the system memory was completely filled up, but this shouldn't be a problem if I understand the memory map process correctly.

I will try to recreate the situation on a VPS and come back to you :-) Thanks for the great support so far!

**Comment by ideoma** [comment]
Unresponsive is a problem. It would be good if you dump thread stacks if it happens with `jstack` or a similar tool for java 

https://www.baeldung.com/java-thread-dump

**Comment by puzpuzpuz** [comment]
What metric do you use to measure memory consumption? Virtual memory size, or RSS (Resident Set Size), or something else? If former, you should be using RSS since it stands for physically resident memory, i.e. occupying space in the machine's RAM.

**Comment by puzpuzpuz** [comment]
> Unresponsive is a problem. It would be good if you dump thread stacks if it happens with `jstack` or a similar tool for java
> 
> https://www.baeldung.com/java-thread-dump

If possible, I'd also recommend running the reproducer query and profiling QuestDB for several seconds (at least, 5-10). This might help us to understand the hot spot.
https://github.com/jvm-profiling-tools/async-profiler

**Comment by mariusziemke** [comment]
Sorry for responding that late, I finally had some time to come back to this issue.. 

Some things that could be important:
- I did a heap dump and its only around ~1GB in total size with 950mb used by `DateLocale`. Don't know if there is another issue because almost 1GB for timezone stuff seems a bit much to me.
- When querying with the HTTP API through /exec the [cairo caching limits](https://github.com/questdb/questdb/issues/1680#issuecomment-993341288) seem to work. At least the RSS only fills up to ~5 GB. Limits do not apply for a postgres client and the corresponding configuration for `pg factory cache` doesn't do anything noticeable regarding the RSS.
- I also created a thread dump but it is not really interesting for my eyes (not a Java developer..)
- The RSS also fills up if I query an empty table. The only important thing is that I use a pg-client and some kind of varying condition (e.g. WHERE timestamp BETWEEN X AND Y)

I probably forgot some things.. If you need the raw dumps or memory + cpu profile we should maybe switch to slack :-)

Thank you in advance.. I will try to do some more research in the next few days.

**Comment by timscchao** [comment]
Hi,

I got similar issue on questDB with Grafana.
The java process's VSZ & RSS keep increasing when I reload the dashboard.
And finaly it cause the system oom-kill.

Here is the 'ps' output
VSZ          RSS
7424680   231468 (start up)
9233040   1844888 (1st reflash)
10412944   2894080 (2nd reflash)
11482232   3845540 (3rd reflash)

My Grafa panel is a repeated panel with around 20 $beacon.
Field 'stype' is symbol, and 'value' is a double column.
```
SELECT stype, value, timestamp FROM readings
LATEST BY tag, stype where
  $__timeFilter(timestamp) and
  tag=$beacon
```

My Env:
- Ubuntu 20.04.3
- QuestDB 6.1.3 on Docker
- Grafana 8.3.3 on Docker

**Comment by puzpuzpuz** [comment]
@timscchao did you try to change the settings as suggested in https://github.com/questdb/questdb/issues/1680#issuecomment-993341288 ?

**Comment by VertigoX64** [comment]
Same issue here.

It seems that with every reload of the Grafana dashboard,  the memory usage increases dramatically and does not shrink afterwards. 
My Grafana connection settings are attached. (please note that I've toyed with the parameters a bit and this screenshot is for the latest unsuccessful config )

![image](https://user-images.githubusercontent.com/19937537/147409189-88b5429c-cb1e-4bf2-bb1b-d06c75bc99a2.png)

**Comment by VertigoX64** [comment]
> @timscchao did you try to change the settings as suggested in [#1680 (comment)](https://github.com/questdb/questdb/issues/1680#issuecomment-993341288) ?

Yes. nothing happened

**Comment by bluestreak01** [comment]
Can you guys run:

`select dump_memory_usage()`

this will dump memory usage breakdown in log

**Comment by VertigoX64** [comment]
Thanks for the quick response.
Here's the dump file as requested.

[stdout-2021-12-26T14-05-31.txt](https://github.com/questdb/questdb/files/7777084/stdout-2021-12-26T14-05-31.txt)

**Comment by VertigoX64** [comment]
Here is the video to reproduce what happens:
Uploading af4GYu1qv9.mp4…

**Comment by VertigoX64** [comment]
Here is the GIF to reproduce what happens:

![fHrEb771cM](https://user-images.githubusercontent.com/19937537/147411575-698e45b8-97fe-4219-bc48-217b542087e7.gif)

**Comment by timscchao** [comment]
> @timscchao did you try to change the settings as suggested in [#1680 (comment)](https://github.com/questdb/questdb/issues/1680#issuecomment-993341288) ?

Sorry for late.
Yes, I did try the cairo.cache settings, but no help.

And here is the memory usage dump in my test env.
`questdb_1  | 2021-12-27T05:50:20.500200Z A dump-memory-usage 
questdb_1  |    TOTAL: 5597868626
questdb_1  |    MMAP_DEFAULT: 237712
questdb_1  |    NATIVE_DEFAULT: 32028682
questdb_1  |    MMAP_O3: 0
questdb_1  |    NATIVE_O3: 134217752
questdb_1  |    NATIVE_RECORD_CHAIN: 0
questdb_1  |    MMAP_TABLE_WRITER: 201351168
questdb_1  |    NATIVE_TREE_CHAIN: 0
questdb_1  |    MMAP_TABLE_READER: 56496
questdb_1  |    NATIVE_COMPACT_MAP: 0
questdb_1  |    NATIVE_FAST_MAP: 520093696
questdb_1  |    NATIVE_LONG_LIST: 4161709568
questdb_1  |    NATIVE_HTTP_CONN: 205563136
questdb_1  |    NATIVE_PGW_CONN: 268435456
questdb_1  |    MMAP_INDEX_READER: 582128
questdb_1  |    MMAP_INDEX_WRITER: 39907328
questdb_1  |    MMAP_INDEX_SLIDER: 33554432
questdb_1  |    MMAP_BLOCK_WRITER: 0
questdb_1  |    NATIVE_REPL: 131072
questdb_1  | `

**Comment by puzpuzpuz** [comment]
> The NATIVE_FAST_MAP and NATIVE_LONG_LIST increasd a lot after reload Grafane.

#1722 should fix that. It'll be included in the next release.

> Yes, I did try the cairo.cache settings, but no help.

Is it too much to ask you to set the following settings and try the experiment one more time? The previously mentioned settings apply to HTTP API, not the pg wire protocol.
```
pg.factory.cache.column.count=1
pg.factory.cache.row.count=1
```

**Comment by VertigoX64** [comment]
> > The NATIVE_FAST_MAP and NATIVE_LONG_LIST increasd a lot after reload Grafane.
> 
> #1722 should fix that. It'll be included in the next release.
> 
> > Yes, I did try the cairo.cache settings, but no help.
> 
> Is it too much to ask you to set the following settings and try the experiment one more time? The previously mentioned settings apply to HTTP API, not the pg wire protocol.
> 
> ```
> pg.factory.cache.column.count=1
> pg.factory.cache.row.count=1
> ```

I tested it. It did not resolve the issue. The memory leak happens nonetheless. 

Thank you.

**Comment by puzpuzpuz** [comment]
> The memory leak happens nonetheless.

@VertigoX64 why do you consider this to be a memory leak? Do you see an unbounded increase in RSS? It is expected that QDB's memory consumption increases on the first and subsequently executed queries since it warms the internal caches. However, there are certain limits for the aforementioned caches and the growth shouldn't be unbounded.

Also, #1722 should make the caching less aggressive when it comes to `LATEST BY` queries.

**Comment by VertigoX64** [comment]
I understand that I might have guessed wrong. However, I've tested the same query on the QuestDB's webui and the memory increase was not as aggressive as Grafana's. This was the reason behind my guess.

**Comment by puzpuzpuz** [comment]
@VertigoX64 could you share your table schema and the query? I'd like to try to reproduce your scenario locally.

**Comment by VertigoX64** [comment]
Thank you.

It's actually the data sent directly from Telegraph's cpu and memory metrics.

P.S. 
Here is the query which ran inside Grafana:

```
SELECT timestamp AS time,
  cpu,
  host,
       avg(100 - usage_idle) as cpu_usage
FROM cpu
WHERE $__timeFilter(timestamp) and cpu!='cpu-total'
SAMPLE BY $__interval
```

**Comment by puzpuzpuz** [comment]
Spotted a problem with setting `pg.factory.cache.*` and `cairo.cache.*` values to `1`. The efficient cache size was 32 entries, not a single one as we expected.

It's going to be fixed by #1735.

**Comment by mariusziemke** [comment]
Awesome! :-) 

Is there some documentation about the caching details? From my understanding data is mapped into memory when querying and just stays there until the space is needed otherwise. What exactly are the `cairo.cache.*` and `pg.factory.cache.*` settings about? 

If I'd cache some data it would be great to have an estimation about how much memory is needed for doing so.

**Comment by VertigoX64** [comment]
Big Thanks!

**Comment by bluestreak01** [comment]
> Awesome! :-)
> 
> Is there some documentation about the caching details? From my understanding data is mapped into memory when querying and just stays there until the space is needed otherwise. What exactly are the `cairo.cache.*` and `pg.factory.cache.*` settings about?
> 
> If I'd cache some data it would be great to have an estimation about how much memory is needed for doing so.

These are SQL statement caches, they are intended for situations where SQL is used together with bind variables. This doesn't seem to be the case with Grafana. The idea was that execution plan together the memory it estimated for data processing is held in cache for reuse. This is not the same as disk cache for memory mapped files.

The intent with Grafana as the client is disable statement cache completely. It is useless unless Grafana is able to reuse SQL text and leverage bind variables.

**Comment by bsmth** [comment]
Hi All, I'm going to close this one for now as it appears changes have landed which fix this.

If the problem is still not resolved in the latest version, feel free to reopen the issue or reply here with more details.

Thank you :)
