### ISSUE TITLE
SIGSEV in find_latest_for_key()

### ISSUE THREAD

**Issue by KendrickAng** [questdb/questdb#1763]
### Describe the bug

Occasionally, questdb crashes with a SIGSEV, but what causes it is still unclear. The corresponding error log is attached, which includes details of the environment quest was running in.

table schema:
```
height - long
hash - string
timestamp - timestamp
pa - symbol
ta - string
oa - string
oamt - long
ra - string
ramt - long
exc - string
```

### Environment

```markdown
- **QuestDB version**: 6.1.3
- **OS**: Ubuntu 20.04
- **Browser**: Not Applicable
```

### Additional context
Quest log (11/01/2022): [questdb-debug-info-error_private.log](https://github.com/questdb/questdb/files/7843090/questdb-debug-info-error_private.log)

Error log (11/01/2022): [hs_err_pid31077_private.log](https://github.com/questdb/questdb/files/7843089/hs_err_pid31077_private.log)

Error log: [hs_err_pid1059.log](https://github.com/questdb/questdb/files/7822432/hs_err_pid1059.log)

**Comment by eugenels** [comment]
Hi Kendrick 
Could you please provide the query which caused the segfault?
I can see it has happened inside the `geohash` type processing function.
But  "hash" column has a `string` type in your schema.

**Comment by KendrickAng** [comment]
Hi Eugene, we haven't managed to find the exact query causing the segfault, since we only enabled error logging. What does this mismatch between `geohash` and `string` mean? Perhaps I can narrow down potential causes if I know more.

**Comment by ideoma** [comment]
Can you copy CREATE TABLE statement from questdb web console? It's right click on table name -> Copy Schema to Clipboard

**Comment by eugenels** [comment]
We have special optimization for geohash type for `latest by` queries (https://questdb.io/docs/concept/geohashes).

It can be a bug in the query parser (column name "hash" with type "geohash" type collision) that triggers the wrong processing function.

**Comment by KendrickAng** [comment]
> Can you copy CREATE TABLE statement from questdb web console? It's right click on table name -> Copy Schema to 

```
CREATE TABLE 'mytable' (height LONG, hash STRING, timestamp TIMESTAMP, pa SYMBOL capacity 256 CACHE index capacity 256, ta STRING, oa STRING, oamt LONG, ra STRING, ramt LONG, exc STRING) timestamp (timestamp) PARTITION BY MONTH;
```

**Comment by ideoma** [comment]
Would be good if you can log the query. If you're concerned about log file size you can switch log partitioning like described here

https://stackoverflow.com/questions/68433005/how-can-i-automatically-delete-log-files-in-questdb

Then you'll need to automate keeping only last log file.

**Comment by KendrickAng** [comment]
Thanks for the link. We have turned on logging and are trying to reproduce the query at the moment. We also tried replaying queries from our nginx logs but couldn't cause the SIGSEV again (we think its nondeterministic). As soon as we manage to reproduce the error, I'll post it here.

**Comment by KendrickAng** [comment]
Hi, if it still matters, I have uploaded an error log with its debug trace into the description. It doesn't say the exact query run since we use kafka connect, but perhaps it might help.

**Comment by bluestreak01** [comment]
hey @KendrickAng we released 6.2. yesterday, which includes this fix

**Comment by EugeneTeu** [comment]
Hey we are still seeing this issue on 6.2.0. CC: @KendrickAng

**Comment by bluestreak01** [comment]
@EugeneTeu do you mind attaching another `hs_err*` file ?

**Comment by EugeneTeu** [comment]
@bluestreak01 hi we will test again and upload the latest. but so far previous times we seen, error seems to be the same hs_err* as previously reported

**Comment by bluestreak01** [comment]
thank you very much for confirming!

**Comment by eugenels** [comment]
hi @EugeneTeu
could you please attach the fresh hs_err log?
