### ISSUE TITLE
Ambiguous column name when using alias in join

### ISSUE THREAD

**Issue by VanshajPoonia** [questdb/questdb#2625]
### Describe the bug

Why does this query produce an "Ambiguous column name" error when I include the "as time" alias? If I remove "as time" or "SAMPLE BY 1d", it goes away.

```
SELECT a.ts as time, sum(a.to_grid), sum(a.from_grid), sum(b.hourly_production)
FROM 'eloverblik' as a, 'ap_systems' as b
WHERE a.ts = b.ts
SAMPLE BY 1d;
```

The schemas are:

```
ap_systems
  ts timestamp
  hourly_production double

eloverblik
  ts timestamp
  to_grid double
  from_grid double
```

The following query using another alias and join syntax have the same issue

```
SELECT e.ts as timecol, sum(e.to_grid), sum(e.from_grid), sum(a.hourly_production)
FROM 'eloverblik' as e INNER JOIN 'ap_systems' as a ON
 (e.ts = a.ts)
SAMPLE BY 1d;
```

**Comment by pswu11** [comment]
Hi, thanks for raising the issue. Could you please provide more context i.e. QuestDB's version?

**Comment by VanshajPoonia** [comment]
> Hi, thanks for raising the issue. Could you please provide more context i.e. QuestDB's version?

Its 6.4.2

**Comment by puzpuzpuz** [comment]
> Its 6.4.2

That's a quite old version. Could you check the latest one, 6.5.3? Chances are high that this issue is already fixed.

**Comment by s-is-coding** [comment]
> > Its 6.4.2
> 
> That's a quite old version. Could you check the latest one, 6.5.3? Chances are high that this issue is already fixed.

That was released 3 months ago I think and hence, a lot of apps are running this version
I tried the latest version too. But the issue is still there :(
