### ISSUE TITLE
Query error 

### ISSUE THREAD

**Issue by yvhk2900** [questdb/questdb#2640]
### Describe the bug

select * from SCSJ where (station_id='6851C124B5CB40E2812B5E050AB331FC') 
 ORDER BY SCSJ.CreateTime desc 

2022-10-14T06:02:56.364197Z I i.q.c.h.p.JsonQueryProcessorState [7588] execute-new [skip: 0, stop: 1000]
2022-10-14T06:02:56.470214Z E i.q.c.h.p.JsonQueryProcessorState [7588] internal error [q=`select * from SCSJ where (station_id='6851C124B5CB40E2812B5E050AB331FC') 
 ORDER BY SCSJ.CreateTime desc 
 LIMIT 26, 30`, ex=
io.questdb.cairo.CairoException: [0] String is outside of file boundary [offset=157918, len=1346109474, size=16777216, fd=8760]
]
2022-10-14T06:02:56.470453Z I i.q.c.h.p.JsonQueryProcessor all sent [fd=7588, lastRequestBytesSent=678, nCompletedRequests=22, totalBytesSent=673992]

### To reproduce

I think there is a problem with the column. d file and the column. i file

### Environment

```markdown
- **QuestDB version:6.0.4
- **OS: windows
- **Browser: chrome 106.0.5249.119
```

**Comment by yvhk2900** [comment]
[column.zip](https://github.com/questdb/questdb/files/9782949/column.zip)
This is a column of the SCSJ table

**Comment by pswu11** [comment]
Hi @yvhk2900  6.0.4 is quite an old version and between this version and the latest 6.5.3 many bugs were fixed. 
It's recommended to upgrade the QuestDB version regularly.

**Comment by yvhk2900** [comment]
QuestDB has been upgraded to 6.5.3. After data migration, the same problem still exists. I think the index is damaged during insertion.

**Comment by bluestreak01** [comment]
Could you drop index and recreate on 6.5.3 ?

**Comment by yvhk2900** [comment]
@bluestreak01 The index is broken, causing some data to be unreadable. What operations are needed to rebuild the index?

**Comment by bluestreak01** [comment]
you can drop it like so:
https://questdb.io/docs/reference/sql/alter-table-alter-column-drop-index/

try without index first to make sure this is indeed index that's causing the problem

you can add index like this:

https://questdb.io/docs/reference/sql/alter-table-alter-column-add-index/
