### ISSUE TITLE
TextImportTask could not import [phase=partition_import, ex= io.questdb.cairo.CairoException: [1455] could not mmap column [fd=2176, size=16777216] ]

### ISSUE THREAD

**Issue by 390029659** [questdb/questdb#2815]
### Describe the bug

use commond “COPY data_hydrometeor FROM 'data_hydrometeor.csv' WITH HEADER true TIMESTAMP 'TIME' FORMAT 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ';”  to import.
![image](https://user-images.githubusercontent.com/16483840/203924596-f73a5a14-c7fa-4d66-83f6-885e38e79ba2.png)
![image](https://user-images.githubusercontent.com/16483840/203925013-45303bee-1c0f-4f2f-865d-c3dcaec65b7a.png)

### To reproduce

1.COPY data_hydrometeor FROM 'data_hydrometeor.csv' WITH HEADER true TIMESTAMP 'TIME' FORMAT 'yyyy-MM-ddTHH:mm:ss.SSSUUUZ
2.SELECT * FROM sys.text_import_log WHERE id = '***' order by ts desc; 
3.error

### Expected Behavior

Import succeeded

### Environment

```markdown
- **QuestDB version**:6.5.1
- **OS**:win10
- **Browser**:chrome 107 （64-bit）
```

**Comment by bluestreak01** [comment]
This is likely to have been fixed

Please try [6.6.1](https://github.com/questdb/questdb/releases/tag/6.6.1)

**Comment by puzpuzpuz** [comment]
@390029659 could you confirm that the issue still persists on the latest version?

**Comment by 390029659** [comment]
> @390029659 could you confirm that the issue still persists on the latest version?

@puzpuzpuz I tried once, but the error did not reappear

**Comment by puzpuzpuz** [comment]
Good to hear that. Let me close the issue. Please reopen it if you face the issue once again.
