### ISSUE TITLE
CSV double import bug

### ISSUE THREAD

**Issue by TheTanc** [questdb/questdb#297]
**Describe the bug**
When importing a `csv`, values of type `double` are subject to add trailing digits. So value `1.234` in the csv might end up being stored as `1.2340000000004` for example.

**Expected behavior**
Values should be imported normally without trailing digits being added.

**Environment (please complete the following information):**
 - AWS linux
 - Version: 4.2

**Screenshots**
<img width="528" alt="Screenshot 2020-05-18 at 11 25 19" src="https://user-images.githubusercontent.com/52114895/82206345-f7d16880-98ff-11ea-8197-15ce59527717.png">

**Comment by TheTanc** [comment]
@bluestreak01 this one is solved correct?

**Comment by bluestreak01** [comment]
It isn't solved unfortunately. We solved double-to-string conversion, but not string-to-double.

We need ZeroGC solution. This means we need IEEE754 converter that would take `CharSequence` as an input (or native memory address) and produce double value without rounding artefacts. Java standard library already has implementation for this but that takes String as an input. Creating string out of every numeric value is sub-optimal

**Comment by Cobalt-27** [comment]
Hi, I would like to work on this issue if it's not fixed yet.

**Comment by Cobalt-27** [comment]
The bug can be triggered with the following test case
`    @Test
    public void testDoubleConversion10Places() throws Exception{
        assertMemoryLeak(
                ()->{
                    compiler.compile("create table tab (val double)",sqlExecutionContext);
                    executeInsert("insert into tab values (111.1111111);");
                    TestUtils.printSql(
                            compiler,
                            sqlExecutionContext,
                            "select val from tab",
                            sink
                    );
                    TestUtils.assertEquals("val\n111.1111111\n", sink);
                }
        );
    }`
It seems that `Numbers.parseDouble()`, as it's mentioned, parses double incorrectly, it simply uses a loop to calculate its value which results in trailing digits. I can write an IEEE754 converter to replace it.

**Comment by Cobalt-27** [comment]
The bug can be triggered with the following test case
```   @Test
    public void testDoubleConversion10Places() throws Exception{
        assertMemoryLeak(
                ()->{
                    compiler.compile("create table tab (val double)",sqlExecutionContext);
                    executeInsert("insert into tab values (111.1111111);");
                    TestUtils.printSql(
                            compiler,
                            sqlExecutionContext,
                            "select val from tab",
                            sink
                    );
                    TestUtils.assertEquals("val\n111.1111111\n", sink);
                }
        );
    }
```
It seems that `Numbers.parseDouble()`, as it's mentioned, parses double incorrectly, it simply uses a loop to calculate its value. I  plan to write an IEEE754 converter to replace it.

**Comment by jerrinot** [comment]
@Cobalt-27 If you are not afraid of math then [this (PDF) paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.45.4152&rep=rep1&type=pdf) looks like a decent start. It's not simple at all, but it could be fun to code it from scratch. 

I looked at Apache Harmony and they use a native parser. Kotlin folks [borrowed the same code](https://github.com/JetBrains/kotlin-native/blob/d1bd91e5b3056f0af12b7c4e73e49dd0206bf56b/runtime/src/main/cpp/dtoa/dblparse.cpp#L441) from Harmony.

**Comment by Cobalt-27** [comment]
> @Cobalt-27 If you are not afraid of math then [this (PDF) paper](https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.45.4152&rep=rep1&type=pdf) looks like a decent start. It's not simple at all, but it could be fun to code it from scratch.
> 
> I looked at Apache Harmony and they use a native parser. Kotlin folks [borrowed the same code](https://github.com/JetBrains/kotlin-native/blob/d1bd91e5b3056f0af12b7c4e73e49dd0206bf56b/runtime/src/main/cpp/dtoa/dblparse.cpp#L441) from Harmony.

Thank you for your advice, I would give it a try.

**Comment by Cobalt-27** [comment]
#### The bug

In the current version, the command

```
select * from (select 111.1111111 as val)
```

returns

```
111.11111109999999 
(printed as 111.111111099999 in web console)
```

It's apparently bugged since double has precision up to 15 digits, and `111.1111111` is only 10 digits long



#### The fix

It can be fixed in a relatively simple way.

When converting a double`111.1111111`, `Numbers.parseDouble()` first turns it into an integer`1111111111`, then return `1111111111* 1E-7` as result. 

`C#`[NumberToDoubleFloatingPointBits](https://source.dot.net/#System.Private.CoreLib/Number.NumberToFloatingPointBits.cs,3b99f12cbc14a09d,references) uses the same method except that in the final step it returns `1111111111 / 1E7`.

The trailing digits are gone when I use the latter approach.

The problem is solved when

```
return (negative ? -val : val) * pow10dNeg[-exp]
```

is replace by

```
return (negative ? -val : val) / pow10d[-exp];
```



#### Tests

```
select * from (select 111.1111111 as val)
```

now returns

```
111.1111111
```



I then generate thousands of 11-15 digits float-point as input, the fixed version produces no trailing digits, while without the fix, it fails in a considerable proportion of tests.

```java
 @Test
    public void TestDoubleConversion() throws SqlException {
        int cases = 1000;
        for(int digits=11;digits<=15;digits++)
            Assert.assertEquals(PassCount(cases,digits), cases);
    }
    public int PassCount(int cases,int digits) throws SqlException{
        int pass = 0;
        char[] s = new char[digits];
        Rnd rnd = new Rnd();
        for (int t = 0; t < cases; t++) {
            for (int i = 0; i < s.length; i++) {
                s[i] = (char) (rnd.nextPositiveInt() % 9 + '1');
            }
            int dp=rnd.nextPositiveInt() % (5)+1;
            Assert.assertTrue(dp<digits);
            s[dp] = '.';
            String numStr=new String(s);
            String expected="val\n"+numStr+"\n";
            TestUtils.printSql(
                    compiler,
                    sqlExecutionContext,
                    "select * from (select "+numStr+" as val)",
                    sink
            );
            if (sink.equals(expected)) {
                pass++;
            } else {
                System.out.println("[Expected]"+expected);
                System.out.println("[Actual]"+sink);
            }
        }
        return pass;
    }
```



After the fix of trailing digits, some tests fail, for instance:

```
988.2230000000001
NaN
988.2230000000001
...

> but was:<a
...
988.223
NaN
988.223
...
```

It seems that it's because an expected value with trailing digits is given, which should be fixed later.

Should I fix those tests before committing a PR?



Also, I don't know why changing `*1E-7` to `/1E7` works, further research is needed.

**Comment by Cobalt-27** [comment]
The difference between these two approaches can be observed by simply executing:
```
System.out.println(1111111111/1E7);
System.out.println(1111111111*1E-7);
```
This works for other cases as well, the second manner becomes broken when handling a large integer.

**Comment by jerrinot** [comment]
Hello @Cobalt-27, thank you for spending time on this! 

You wrote: _[...] since double has precision up to 15 digits, and 111.1111111 is only 10 digits long_ 
Are you sure about this statement? Double gives you 52 fraction bits and some seemingly simple numbers won't fit into it. For example, try to convert the number 1.1 into binary. It won't fit. Thus some error is expected, the goal of the parser is to minimize the error margin. 

Your test is encouraging, but it would be good to understand what is going on. Because this helps you to reason about possible ways it could backfire. I'm certainly not an expert on this, I'm mostly learning this on the go. FWIW: Your link to C# code helped to find to find a nice paper on this topic, you might find it interesting too: https://arxiv.org/pdf/2101.11408.pdf

**Comment by Cobalt-27** [comment]
> Hello @Cobalt-27, thank you for spending time on this!
> 
> You wrote: _[...] since double has precision up to 15 digits, and 111.1111111 is only 10 digits long_ Are you sure about this statement? Double gives you 52 fraction bits and some seemingly simple numbers won't fit into it. For example, try to convert the number 1.1 into binary. It won't fit. Thus some error is expected, the goal of the parser is to minimize the error margin.
> 
> Your test is encouraging, but it would be good to understand what is going on. Because this helps you to reason about possible ways it could backfire. I'm certainly not an expert on this, I'm mostly learning this on the go. FWIW: Your link to C# code helped to find to find a nice paper on this topic, you might find it interesting too: https://arxiv.org/pdf/2101.11408.pdf

Thanks, that's really helpful. I will spend some time working on this paper to make sure this practice is indeed correct.

As for the '15 decimal digits',  `111.11111109999999 ` may not be a wrong answer, thanks again for pointing out this mistake.

So instead of claiming that the fixed method can obtain a result with less error, it should be said that this method returns the one that can be printed without trailing digits, through Questdb's native function and `String.valueOf`.

**Comment by Cobalt-27** [comment]
Hello @jerrinot, I have read the pre-mentioned [(PDF) How to Read Floating Point Numbers Accurately (researchgate.net)](https://www.researchgate.net/publication/2295884_How_to_Read_Floating_Point_Numbers_Accurately), and I would like to explain why we should use `/1E7k` but not `*1E-k` when `k` is a positive integer.



#### what's wrong with Questdb's parse method?

The paper's author claims that for `f*10^e`:

1. If `f and (10^e)` can both be represented exactly using an n-bit floating point(double in this case), then `f*10pow[e]` is always the best n-bit floating-point approximation
2. If `f and (10^-e)` can both be represented exactly using an n-bit floating point, then `f/10pow[-e]` is always the best approximation



Take `1111111111*10^-7` as an example,

`1111111111=1111111111*2^0`, can be accurately expressed as a double

so does `1E7=10^7=(5^7) * 2^7`, and the other `1Ex, x=1...22`

However `0.1,0.01...1E-7`can not be accurately represented in double.

So according to the theory, `1111111111/10pow[7]` is the best approximation, but `1111111111*10powNeg[7]` is not guaranteed to be the best one.

**Comment by Cobalt-27** [comment]
That theory can't cover all cases for `f*10^e`, for instance: what if both `10^e` and `10^-e` are too large for double to be accurately represented.

The paper offers a "slow path" to handle these circumstances, while C# adopts a different slow path(https://arxiv.org/pdf/2101.11408.pdf), but they all share the same fast path.

**Comment by Cobalt-27** [comment]
In summary:
1. the majority of inputs can be handled by the "fast path": questdb's parseDouble() is a wrong implementation of the fast path whose outputs are not guaranteed to be the best approximation.
2. long inputs should be parsed using a "slow path" with higher precision: sadly current questdb has no such a method, it would use the fast path and obtain a sub-optimal result.

**Comment by newskooler** [comment]
FWIW it's not a bug only on CSV import I believe. I see in my data too (ILP stream) and was wondering what it is... 
Very annoying - thanks for raising it and attempting to solve 🙏

**Comment by jerrinot** [comment]
@Cobalt-27: cool analysis, thanks for spending your energy on it, much appreciated! 
Are you planning to send a Pull Request to fix the fast path?

**Comment by Cobalt-27** [comment]
> @Cobalt-27: cool analysis, thanks for spending your energy on it, much appreciated! Are you planning to send a Pull Request to fix the fast path?

Yes, I will send a pr later, also, thank you for giving me some helpful advice on this issue.

**Comment by jerrinot** [comment]
fixed by #2055
Massive Thank You to @Cobalt-27!
