### ISSUE TITLE
Different results of SELECT query with and without using LIMIT in query

### ISSUE THREAD

**Issue by niksbanna** [questdb/questdb#3783]
### Describe the bug

While building my app I found something weird I got different results of the same SELECT query with and without using LIMIT with it.
Here is the query I am taking about...
`     SELECT
            timestamp AS date,
            gp,
            cp,
            grid_p,
            ROUND((gp/1000) * 8, 0) AS import_grid,
            ROUND((grid_p/1000) * 8, 0) AS export_grid,
            ROUND(((grid_p/1000) * 8) / 1000, 2) AS net_exports
            FROM device_data
            WHERE device_data.gsm_id = '12345678'
            ORDER BY timestamp DESC LIMIT 1;`

I am creating an app that returns the Solar power analytics so I created a `device_data` table where I store all the power details like gp, cp, grid_p, and gsm_id. In this query, I am trying to select the recent data of that gsm_id and fetch other kinds of stuff with calculations like import_grid.

Here is the result of this query:
`"rows": [
        {
            "date": "2023-08-17T01:42:26.276Z",
            "gp": 7385.43,
            "cp": 14096.14,
            "grid_p": 6710.71,
            "import_grid": 59,
            "export_grid": 54,
            "net_exports": 0.05
        }
    ],`

and when I run the same query without `LIMIT 1` I get different results on the first row which comes in descending order and which is the correct data stored in the table.

I can't show you the response because it is larger data in size but I checked it on Questdb panel (localhost:9000)
![image](https://github.com/questdb/questdb/assets/45920258/72bef2b2-38fa-4944-a9c3-92eda9c21c16)
![image](https://github.com/questdb/questdb/assets/45920258/0c619035-37b5-425a-a33f-db3f0434c2d8)

### Environment

```markdown
- **QuestDB version*7.2.1*:
- **OS** *linux-amd64*:
- **Browser** *Chrome*:
```

**Comment by ideoma** [comment]
Probably related to https://github.com/questdb/questdb/pull/3711 and should be fixed in 7.3.2

**Comment by niksbanna** [comment]
I have upgraded to version 7.3.2 in my Ubuntu but this problem still exists.
